### ISSUE TITLE
library issue

### ISSUE THREAD

**Issue by RustoMCSpit** [erroreyes/crrshrr#5]
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/chris/.claps/crrshrr.clap)

i updated my system

**Comment by erroreyes** [comment]
I build the Linux binaries using Github actions and Ubuntu 20.04 since other nih-plugs based plugins are also built this way. Please try the new binaries from https://github.com/erroreyes/crrshrr/actions/runs/9324073159/artifacts/1557572220 and let me know if you can run it.

**Comment by RustoMCSpit** [comment]
yeah it runs now!
